name: Test and publish

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    container: node
    env:
      REMOTE_HOST: "tools-dev.wmflabs.org"
      REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
    #  STARTUP_SCRIPT: |
    # options: -e REMOTE_HOST -e REMOTE_USER -e SSH_PRIVATE_KEY -e STARTUP_SCRIPT
    steps:
      - run: |
          set -eu
          mkdir -p ~/.ssh
          echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -4 -o StrictHostKeyChecking=no -N -D 8080 "${REMOTE_USER}@${REMOTE_HOST}" &
          SSH_JOB=$!
          trap "kill $SSH_JOB" EXIT

          curl -L -x socks5h://localhost:8443 https://ru.wikipedia.org/
