name: Test and publish

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create script
        run: |
            cat << 'EOF' > runme.sh
            #!/usr/bin/env sh

            echo -e "$SSH_PRIVATE_KEY" | md5sum
            echo -e "$SSH_PRIVATE_KEY" | head -c 40
            echo -e "HOME=$HOME"
            echo -e "NODE_VERSION=$NODE_VERSION"
            echo -e "HOSTNAME=$HOSTNAME"
            echo -e "PATH=$PATH"

            set -eu
            mkdir -p ~/.ssh
            echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            echo timeout 10s ssh -v -4 -o StrictHostKeyChecking=no -N -D 8080 "${REMOTE_USER}@${REMOTE_HOST}"

            #SSH_JOB=$!
            #trap "kill $SSH_JOB" EXIT
            #curl -L -x socks5h://localhost:8443 https://ru.wikipedia.org/

            # options: -e REMOTE_HOST -e REMOTE_USER -e SSH_PRIVATE_KEY -e STARTUP_SCRIPT
            EOF
            chmod +x runme.sh

      - name: Magic
        env:
          REMOTE_HOST: "tools-dev.wmflabs.org"
          REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
        run: |
          ./runme.sh
        

#       - name: Magic
#         uses: docker://node:latest
#         env:
#           REMOTE_HOST: "tools-dev.wmflabs.org"
#           REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
#           SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
#         with:
#           entrypoint: runme.sh
 
